controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters: {}

diff_drive_controller:
  ros__parameters:
    cmd_vel_topic: /cmd_vel
    publish_rate: 50.0
    cmd_vel_timeout: 0.25

    use_stamped_vel: false
    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']

    wheel_separation: 0.35
    wheel_radius: 0.05